EXPERIMENT:
  NAME: ""
  TAG: "dtkd,res50,mv2"
  PROJECT: "DTKD_Final"
DISTILLER:
  TYPE: "DTKD"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DTKD:
  ALPHA: 3.0
  BETA: 2.0
